spring:
  datasource:
    url: jdbc:postgresql://db:5432/leboncoin
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8080

# Configuration JWT
jwt:
  secret: VotreSecretJWTSuperLongEtSecurisePourLaProductionDevraitEtreDansUnFichierEnvironnement
  expiration: 86400000 # 24 heures en millisecondes

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9000}
  external-endpoint: ${MINIO_EXTERNAL_ENDPOINT:http://localhost:9000}
  access-key: ${MINIO_ACCESS_KEY:minioadmin}
  secret-key: ${MINIO_SECRET_KEY:minioadmin}
  bucket: ${MINIO_BUCKET:leboncoin-ads}
  secure: ${MINIO_SECURE:false}
  presigned-url-duration: ${MINIO_PRESIGNED_URL_DURATION:PT1H}
